### ISSUE TITLE
NF equation for osmotic pressure may be inaccurate at high salinities

### ISSUE THREAD

**Issue by rkingsbury** [rodoulak/desalsim#11]
In the Mathematical Description, Eq. A. 9 indicates that osmotic pressure in the Nanofiltration model is calculated according to the Van't Hoff equation:

![image](https://github.com/user-attachments/assets/66bf2f1d-3fce-4d4e-a67e-62ab42e598c1)

This equation is only valid at dilute concentrations. It's accuracy can be visualized in the plot below. 

![image](https://github.com/user-attachments/assets/82b92480-39ac-4baa-ad27-b8ebb42e5fbf)

Since the stated purpose of `desalsim` is to analyze brine management technologies, and since osmotic pressure plays a major role in determining the energy requirements of NF and reverse osmosis, use of this equation in the model should be reconsidered. 

At a minimum, osmotic pressure should be computed using the Gibbs equation based on water activity, as described [here](https://pyeql.readthedocs.io/en/latest/class_solution.html#pyEQL.Solution.osmotic_pressure). The water activity could be approximated as the mole fraction of water if necessary; even this simplification should be much more accurate than Eq. A.9 when salt concentrations exceed that of seawater.

**Comment by rodoulak** [comment]
Thank you for your valuable feedback. Based on your suggestion, the nanofiltration function has been revised to calculate the osmotic pressure using the Gibbs equation:
$\pi = -\left( \frac{RT}{V} \right) \ln(a_w)$
where we approximate the water activity α<sub>w </sub> as the mole fraction of water. This adjustment provides a more accurate estimation of osmotic pressure, aligning with the theoretical foundations you highlighted.

In addition:

- The package has been updated on GitHub, and a detailed changelog is provided in the [new release](https://github.com/rodoulak/desalsim/releases), explaining the revisions made to the nanofiltration function and the rationale behind them.
- Example files and tutorials ([NF tutorial](https://github.com/rodoulak/desalsim/blob/main/Tutorials/NF_Tutorial.md#3-use-osmoticpressure-class:~:text=3.%20Use%20OsmoticPressure%20class), [example 1 tutorial](https://github.com/rodoulak/desalsim/blob/main/Tutorials/Example_1_Tutorial.md#:~:text=is%2070.73g/l-,Calculate%20Osmotic%20Pressure,-For%20the%20calculation)) have been updated to reflect this new calculation approach, ensuring that users have clear guidance on using the revised function.
