### ISSUE TITLE
link documentation from README or elsewhere

### ISSUE THREAD

**Issue by rkingsbury** [rodoulak/desalsim#12]
There is a very nice [ReadtheDocs documentation page](https://desalsim-web.readthedocs.io/en/latest/) availble for this package, but as far as I can tell, it is not linked anywhere in the README file or the tutorials. It should be linked so that it is discoverable by users.

**Comment by rodoulak** [comment]
Thank you for pointing that out! I’ve made the following updates:
ReadTheDocs Link in README: I have ensured that the link to the ReadTheDocs documentation page is prominently included in the README file, under the [documentation section](https://github.com/rodoulak/desalsim/tree/main#:~:text=Documentation,at%20Desalsim.), making it easily accessible for users visiting the GitHub repository.

**Comment by rkingsbury** [comment]
Thanks @rodoulak
